theme = "nord"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-pairs = false
auto-format = true
auto-completion = true 

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
max-wrap = 25 #increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[keys.normal]
X = "extend_line_above"

[editor.lsp]
display-messages = true
display-inlay-hints = true

